random-xs:
    sustech-ood: 
      docker-tag: neurips23-ood-sustech-ood
      module: neurips23.ood.sustech-ood.SUSTech-OOD
      constructor: IndexGraphOOD
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"M":5, "ef":100, "cluster_num":1}]
          query-args: |
            [{"ef":20, "nprobe":5}]
text2image-10M:
    sustech-ood: 
      docker-tag: neurips23-ood-sustech-ood
      module: neurips23.ood.sustech-ood.SUSTech-OOD
      constructor: IndexGraphOOD
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"M":20, "ef":1200, "cluster_num":1000}]
          query-args: |
            [{"ef":95, "nprobe":30},
             {"ef":115, "nprobe":30},
             {"ef":125, "nprobe":30},
             {"ef":130, "nprobe":30},
             {"ef":135, "nprobe":30},
             {"ef":140, "nprobe":30},
             {"ef":145, "nprobe":30},
             {"ef":155, "nprobe":30},
             {"ef":175, "nprobe":30}]
