random-filter-s:
    parlayivf:
      docker-tag: neurips23-filter-parlayivf
      module: neurips23.filter.parlayivf.parlayivf
      constructor: ParlayIVF
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"cluster_size": 5000, 
              "T": 8,
              "cutoff": 10000,
              "max_iter": 10,
              "weight_classes": [100000, 400000],
              "build_params": [{"max_degree": 8,
                                "limit": 200,
                                "alpha": 1.175},
                              {"max_degree": 10,
                               "limit": 200,
                               "alpha": 1.175},
                              {"max_degree": 12,
                               "limit": 200,
                               "alpha": 1.175}],
              "bitvector_cutoff": 10000
            }]
          query-args: |
            [{"target_points": 15000,
              "tiny_cutoff": 60000,
              "beam_widths": [70, 70, 70]
              }]

yfcc-10M:
    parlayivf:
      docker-tag: neurips23-filter-parlayivf
      module: neurips23.filter.parlayivf.parlayivf
      constructor: ParlayIVF
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"cluster_size": 5000, 
              "T": 8,
              "cutoff": 10000,
              "max_iter": 10,
              "weight_classes": [100000, 400000],
              "build_params": [{"max_degree": 8,
                                "limit": 200,
                                "alpha": 1.175},
                              {"max_degree": 10,
                               "limit": 200,
                               "alpha": 1.175},
                              {"max_degree": 12,
                               "limit": 200,
                               "alpha": 1.175}],
              "bitvector_cutoff": 10000
            }]
          query-args: |
            [{"target_points": 5000,
              "tiny_cutoff": 30000,
              "beam_widths": [85, 50, 95],
              "search_limits": [500, 500, 500]
              },
              {"target_points": 7500,
               "tiny_cutoff": 35000,
               "beam_widths": [55, 55, 55]
               },
               {"target_points": 5000,
              "tiny_cutoff": 28000,
              "beam_widths": [90, 57, 90],
              "search_limits": [500, 500, 500]
              },
              {"target_points": 15000,
               "tiny_cutoff": 100000,
               "beam_widths": [60, 60, 60]
              },
              {"target_points": 15000,
               "tiny_cutoff": 60000,
               "beam_widths": [90, 90, 90]
              },
              {"target_points": 15000,
               "tiny_cutoff": 100000,
               "beam_widths": [90, 90, 90]
              },
              {"target_points": 15000,
               "tiny_cutoff": 60000,
               "beam_widths": [50, 50, 50]
              },
              {"target_points": 15000,
               "tiny_cutoff": 100000,
               "beam_widths": [50, 50, 50]
              },
              {"target_points": 15000,
               "tiny_cutoff": 60000,
               "beam_widths": [40, 40, 40]
              },
              {"target_points": 15000,
               "tiny_cutoff": 100000,
               "beam_widths": [40, 40, 40]
              }]
