random-xs:
  candy_lvq:
    docker-tag: neurips23-streaming-candy_lvq
    module: neurips23.streaming.candy_lvq.candy_lvq
    constructor: candy_lvq
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "lvqNaive"}]
        query-args: |
            [{"ef":30}, {"ef":50}, {"ef":100}]
random-xs128:
  candy_lvq:
    docker-tag: neurips23-streaming-candy_lvq
    module: neurips23.streaming.candy_lvq.candy_lvq
    constructor: candy_lvq
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "lvqNaive"}]
        query-args: |
            [{"ef":30}, {"ef":50}, {"ef":100}]
msturing-10M-clustered:
  candy_lvq:
    docker-tag: neurips23-streaming-candy_lvq
    module: neurips23.streaming.candy_lvq.candy_lvq
    constructor: candy_lvq
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "lvqNaive"}]
        query-args: |
          [{"ef":30}, {"ef":50}, {"ef":100}]
