sparse-full:
  pinecone_smips:
    docker-tag: neurips23-sparse-pinecone_smips
    module: neurips23.sparse.pinecone_smips.pinecone_smips
    constructor: PineconeSMIPS
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"num_threads": 8, "index_path": "data/pinecone/sparse/index/"}]
        query-args: |
          [
          {"nprobe":8, "top_kprime":26, "ip_budget": 350},
          {"nprobe":8, "top_kprime":28, "ip_budget": 325},
          {"nprobe":8, "top_kprime":30, "ip_budget": 300},
          {"nprobe":8, "top_kprime":30, "ip_budget": 280},
          {"nprobe":8, "top_kprime":30, "ip_budget": 260},
          {"nprobe":8, "top_kprime":30, "ip_budget": 240},
          {"nprobe":8, "top_kprime":30, "ip_budget": 220},
          {"nprobe":8, "top_kprime":30, "ip_budget": 200},
          {"nprobe":8, "top_kprime":32, "ip_budget": 280},
          {"nprobe":8, "top_kprime":34, "ip_budget": 260}]