sparse-small:
    sustech-whu:
      docker-tag: neurips23-sparse-sustech-whu
      module: neurips23.sparse.sustech-whu.SUSTech-WHU 
      constructor: HnswSparse
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"M":16,"ef":200}]
          query-args: |
            [{"ef":10},{"ef":20},{"ef":32},{"ef":60},{"ef":70}]
sparse-1M:
    sustech-whu:
      docker-tag: neurips23-sparse-sustech-whu
      module: neurips23.sparse.sustech-whu.SUSTech-WHU 
      constructor: HnswSparse
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"M":20,"ef":200}]
          query-args: |
            [{"ef":10},{"ef":20},{"ef":32},{"ef":60},{"ef":70},{"ef":80}]
sparse-full:
    sustech-whu:
      docker-tag: neurips23-sparse-sustech-whu
      module: neurips23.sparse.sustech-whu.SUSTech-WHU 
      constructor: HnswSparse
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"M":20,"ef":1200}]
          query-args: |
            [{"ef":20},{"ef":32},{"ef":40},{"ef":45},{"ef":60},{"ef":70},{"ef":80}]
          