random-xs:
    puck:
      docker-tag: neurips23-streaming-puck
      module: neurips23.streaming.puck.puck
      constructor: Puck
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
                [
                    { "index_type": 1, "C":200, "F":200, "FN":8, "N":0}
                ]
          query-args: |
                [
                    {"radius_rate":1.00 ,"search_coarse_count":200, "filter_topk":1000 }                   
                ]

random-xs-clustered:
    puck:
      docker-tag: neurips23-streaming-puck
      module: neurips23.streaming.puck.puck
      constructor: Puck
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
                [
                    { "index_type": 1, "C":200, "F":200, "FN":8, "N":0}
                ]
          query-args: |
                [
                    {"radius_rate":1.00 ,"search_coarse_count":200, "filter_topk":1000 }                   
                ]

msturing-10M-clustered:
    puck:
      docker-tag: neurips23-streaming-puck
      module: neurips23.streaming.puck.puck
      constructor: Puck
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
                [
                    { "index_type": 1, "C":200, "F":200, "FN":8, "N":0}
                ]
          query-args: |
                [
                    {"radius_rate":1.00 ,"search_coarse_count":200, "filter_topk":1000 }                   
                ]

msturing-30M-clustered:
    puck:
      docker-tag: neurips23-streaming-puck
      module: neurips23.streaming.puck.puck
      constructor: Puck
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
                [
                    { "index_type": 1, "C":200, "F":200, "FN":8, "N":0}
                ]
          query-args: |
                [
                    {"radius_rate":1.00 ,"search_coarse_count":200, "filter_topk":1000 }                   
                ]


