sparse-small:
    linscan:
      docker-tag: neurips23-sparse-linscan
      module: neurips23.sparse.linscan.linscan 
      constructor: Linscan
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{}]
          query-args: |
            [{"budget":1},{"budget":0.5},{"budget":0.4},{"budget":0.3},{"budget":0.25},{"budget":0.2},{"budget":0.15},{"budget":0.1},{"budget":0.075},{"budget":0.05}]
sparse-1M:
    linscan:
      docker-tag: neurips23-sparse-linscan
      module: neurips23.sparse.linscan.linscan
      constructor: Linscan
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{}]
          query-args: |
            [{"budget":0.5},{"budget":1},{"budget":2},{"budget":4},{"budget":5},{"budget":6},{"budget":7},{"budget":8},{"budget":10}]
sparse-full:
    linscan:
      docker-tag: neurips23-sparse-linscan
      module: neurips23.sparse.linscan.linscan
      constructor: Linscan
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{}]
          query-args: |
            [{"budget":5},{"budget":15},{"budget":35},{"budget":50},{"budget":52.5},{"budget":55},{"budget":57.5},{"budget":60},{"budget":90},{"budget":500}]
          