random-xs:
    puck:
      docker-tag: neurips23-ood-puck
      module: neurips23.ood.puck.puck
      constructor: Puck
      base-args: ["@metric"]
      run-groups:
        base:
          args: [{"index_type":2, "C":1000, "F":1000,"tinker_neighborhood":16,"tinker_construction":200}]
          query-args: |
                [
                  {"search_coarse_count":50, "tinker_search_range": 100},
                  {"search_coarse_count":50, "tinker_search_range": 200},
                  {"search_coarse_count":50, "tinker_search_range": 300}
                ]


text2image-10M:
    puck:
      docker-tag: neurips23-ood-puck
      module: neurips23.ood.puck.puck
      constructor: Puck
      base-args: ["@metric"]
      run-groups:
        base:
          args: [{"index_type":2, "C":1000, "F":1000,"tinker_neighborhood":16,"tinker_construction":200}]
          query-args: |
                [
                  {"search_coarse_count":10, "tinker_search_range": 190},
                  {"search_coarse_count":10, "tinker_search_range": 160},
                  {"search_coarse_count":10, "tinker_search_range": 165},
                  {"search_coarse_count":10, "tinker_search_range": 170},
                  {"search_coarse_count":10, "tinker_search_range": 175}
                ] 
