sparse-small:
    nle:
      docker-tag: neurips23-sparse-nle
      module: neurips23.sparse.nle.nle 
      constructor: NLE
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"t1":32,"t2":128}]
          query-args: |
            [
            {"k1":4,"k2":40,"k3":150},{"k1":4,"k2":40,"k3":200},
            {"k1":4,"k2":40,"k3":75},{"k1":4,"k2":40,"k3":125},
            {"k1":4,"k2":40,"k3":100},
            {"k1":4,"k2":40,"k3":1},
            {"k1":4,"k2":40,"k3":10},
            {"k1":4,"k2":40,"k3":1000},
            {"k1":4,"k2":40,"k3":0.1},{"k1":4,"k2":40,"k3":50}]
    NLE-Full:
      docker-tag: neurips23-sparse-nle
      module: neurips23.sparse.nle.nle 
      constructor: NLE
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"t1":8,"t2":128},{"t1":16,"t2":128},{"t1":32,"t2":128},{"t1":50,"t2":128},{"t1":128,"t2":128}]
          query-args: |
            [
            {"k1":2,"k2":40,"k3":0.1},
            {"k1":2,"k2":40,"k3":1},
            {"k1":2,"k2":40,"k3":10},
            {"k1":2,"k2":40,"k3":100},
            {"k1":2,"k2":40,"k3":1000},
            {"k1":3,"k2":40,"k3":0.1},
            {"k1":3,"k2":40,"k3":1},
            {"k1":3,"k2":40,"k3":10},
            {"k1":3,"k2":40,"k3":100},
            {"k1":3,"k2":40,"k3":1000},
            {"k1":4,"k2":40,"k3":0.1},
            {"k1":4,"k2":40,"k3":1},
            {"k1":4,"k2":40,"k3":10},
            {"k1":4,"k2":40,"k3":100},
            {"k1":4,"k2":40,"k3":1000},
            {"k1":5,"k2":40,"k3":0.1},
            {"k1":5,"k2":40,"k3":1},
            {"k1":5,"k2":40,"k3":10},
            {"k1":5,"k2":40,"k3":100},
            {"k1":5,"k2":40,"k3":1000},
            {"k1":6,"k2":40,"k3":0.1},
            {"k1":6,"k2":40,"k3":1},
            {"k1":6,"k2":40,"k3":10},
            {"k1":6,"k2":40,"k3":100},
            {"k1":6,"k2":40,"k3":1000}]
sparse-1M:
    nle:
      docker-tag: neurips23-sparse-nle
      module: neurips23.sparse.nle.nle 
      constructor: NLE
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"t1":32,"t2":128}]
          query-args: |
            [
            {"k1":4,"k2":40,"k3":150},{"k1":4,"k2":40,"k3":200},
            {"k1":4,"k2":40,"k3":75},{"k1":4,"k2":40,"k3":125},
            {"k1":4,"k2":40,"k3":100},
            {"k1":4,"k2":40,"k3":1},
            {"k1":4,"k2":40,"k3":10},
            {"k1":4,"k2":40,"k3":1000},
            {"k1":4,"k2":40,"k3":0.1},{"k1":4,"k2":40,"k3":50}]
    NLE-Full:
      docker-tag: neurips23-sparse-nle
      module: neurips23.sparse.nle.nle 
      constructor: NLE
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"t1":8,"t2":128},{"t1":16,"t2":128},{"t1":32,"t2":128},{"t1":50,"t2":128},{"t1":128,"t2":128}]
          query-args: |
            [
            {"k1":2,"k2":40,"k3":0.1},
            {"k1":2,"k2":40,"k3":1},
            {"k1":2,"k2":40,"k3":10},
            {"k1":2,"k2":40,"k3":100},
            {"k1":2,"k2":40,"k3":1000},
            {"k1":3,"k2":40,"k3":0.1},
            {"k1":3,"k2":40,"k3":1},
            {"k1":3,"k2":40,"k3":10},
            {"k1":3,"k2":40,"k3":100},
            {"k1":3,"k2":40,"k3":1000},
            {"k1":4,"k2":40,"k3":0.1},
            {"k1":4,"k2":40,"k3":1},
            {"k1":4,"k2":40,"k3":10},
            {"k1":4,"k2":40,"k3":100},
            {"k1":4,"k2":40,"k3":1000},
            {"k1":5,"k2":40,"k3":0.1},
            {"k1":5,"k2":40,"k3":1},
            {"k1":5,"k2":40,"k3":10},
            {"k1":5,"k2":40,"k3":100},
            {"k1":5,"k2":40,"k3":1000},
            {"k1":6,"k2":40,"k3":0.1},
            {"k1":6,"k2":40,"k3":1},
            {"k1":6,"k2":40,"k3":10},
            {"k1":6,"k2":40,"k3":100},
            {"k1":6,"k2":40,"k3":1000}]
sparse-full:
    nle:
      docker-tag: neurips23-sparse-nle
      module: neurips23.sparse.nle.nle 
      constructor: NLE
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"t1":32,"t2":128}]
          query-args: |
            [
            {"k1":4,"k2":40,"k3":150},{"k1":4,"k2":40,"k3":200},
            {"k1":4,"k2":40,"k3":75},{"k1":4,"k2":40,"k3":125},
            {"k1":4,"k2":40,"k3":100},
            {"k1":4,"k2":40,"k3":1},
            {"k1":4,"k2":40,"k3":10},
            {"k1":4,"k2":40,"k3":1000},
            {"k1":4,"k2":40,"k3":0.1},{"k1":4,"k2":40,"k3":50}]
    NLE-Full:
      docker-tag: neurips23-sparse-nle
      module: neurips23.sparse.nle.nle 
      constructor: NLE
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"t1":8,"t2":128},{"t1":16,"t2":128},{"t1":32,"t2":128},{"t1":50,"t2":128},{"t1":128,"t2":128}]
          query-args: |
            [
            {"k1":2,"k2":40,"k3":0.1},
            {"k1":2,"k2":40,"k3":1},
            {"k1":2,"k2":40,"k3":10},
            {"k1":2,"k2":40,"k3":100},
            {"k1":2,"k2":40,"k3":1000},
            {"k1":3,"k2":40,"k3":0.1},
            {"k1":3,"k2":40,"k3":1},
            {"k1":3,"k2":40,"k3":10},
            {"k1":3,"k2":40,"k3":100},
            {"k1":3,"k2":40,"k3":1000},
            {"k1":4,"k2":40,"k3":0.1},
            {"k1":4,"k2":40,"k3":1},
            {"k1":4,"k2":40,"k3":10},
            {"k1":4,"k2":40,"k3":100},
            {"k1":4,"k2":40,"k3":1000},
            {"k1":5,"k2":40,"k3":0.1},
            {"k1":5,"k2":40,"k3":1},
            {"k1":5,"k2":40,"k3":10},
            {"k1":5,"k2":40,"k3":100},
            {"k1":5,"k2":40,"k3":1000},
            {"k1":6,"k2":40,"k3":0.1},
            {"k1":6,"k2":40,"k3":1},
            {"k1":6,"k2":40,"k3":10},
            {"k1":6,"k2":40,"k3":100},
            {"k1":6,"k2":40,"k3":1000}]
