random-xs:
  zilliz:
    docker-tag: neurips23-ood-zilliz
    module: neurips23.ood.zilliz.zilliz
    constructor: Zilliz
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"R":32, "L":50}]
        query-args: |
          [{"ef":30}, {"ef":50}, {"ef":100}]
text2image-10M:
  zilliz:
    docker-tag: neurips23-ood-zilliz
    module: neurips23.ood.zilliz.zilliz
    constructor: Zilliz
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"R":48, "L":500, "buildthreads" : 8}]
        query-args: |
          [
          {"ef":90},
          {"ef":95},
          {"ef":100},
          {"ef":102},
          {"ef":104},
          {"ef":106},
          {"ef":108},
          {"ef":110},
          {"ef":115},
          {"ef":120}
          ]
